/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_phonygames_pengine_audio_jni_PFmodInterface */

#ifndef _Included_com_phonygames_pengine_audio_jni_PFmodInterface
#define _Included_com_phonygames_pengine_audio_jni_PFmodInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_phonygames_pengine_audio_jni_PFmodInterface
 * Method:    __init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phonygames_pengine_audio_jni_PFmodInterface__1_1init
  (JNIEnv *, jclass);

/*
 * Class:     com_phonygames_pengine_audio_jni_PFmodInterface
 * Method:    __close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phonygames_pengine_audio_jni_PFmodInterface__1_1close
  (JNIEnv *, jclass);

/*
 * Class:     com_phonygames_pengine_audio_jni_PFmodInterface
 * Method:    __update
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phonygames_pengine_audio_jni_PFmodInterface__1_1update
  (JNIEnv *, jclass);

/*
 * Class:     com_phonygames_pengine_audio_jni_PFmodInterface
 * Method:    setSystemParameterByName
 * Signature: (Ljava/lang/String;FZ)V
 */
JNIEXPORT void JNICALL Java_com_phonygames_pengine_audio_jni_PFmodInterface_setSystemParameterByName
  (JNIEnv *, jclass, jstring, jfloat, jboolean);

/*
 * Class:     com_phonygames_pengine_audio_jni_PFmodInterface
 * Method:    loadBank
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_phonygames_pengine_audio_jni_PFmodInterface_loadBank
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_phonygames_pengine_audio_jni_PFmodInterface
 * Method:    unloadBank
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_phonygames_pengine_audio_jni_PFmodInterface_unloadBank
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_phonygames_pengine_audio_jni_PFmodInterface
 * Method:    isBankLoaded
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_phonygames_pengine_audio_jni_PFmodInterface_isBankLoaded
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_phonygames_pengine_audio_jni_PFmodInterface
 * Method:    getEventInstance
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_phonygames_pengine_audio_jni_PFmodInterface_getEventInstance
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_phonygames_pengine_audio_jni_PFmodInterface
 * Method:    startPlaybackForEventInstance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_phonygames_pengine_audio_jni_PFmodInterface_startPlaybackForEventInstance
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_phonygames_pengine_audio_jni_PFmodInterface
 * Method:    __stopPlaybackForEventInstance
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_phonygames_pengine_audio_jni_PFmodInterface__1_1stopPlaybackForEventInstance
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_phonygames_pengine_audio_jni_PFmodInterface
 * Method:    releaseEventInstance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_phonygames_pengine_audio_jni_PFmodInterface_releaseEventInstance
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_phonygames_pengine_audio_jni_PFmodInterface
 * Method:    eventInstanceExists
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_phonygames_pengine_audio_jni_PFmodInterface_eventInstanceExists
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_phonygames_pengine_audio_jni_PFmodInterface
 * Method:    setEventInstancePitch
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_phonygames_pengine_audio_jni_PFmodInterface_setEventInstancePitch
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_phonygames_pengine_audio_jni_PFmodInterface
 * Method:    setEventInstanceVolume
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_phonygames_pengine_audio_jni_PFmodInterface_setEventInstanceVolume
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_phonygames_pengine_audio_jni_PFmodInterface
 * Method:    setEventInstancePaused
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_phonygames_pengine_audio_jni_PFmodInterface_setEventInstancePaused
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_phonygames_pengine_audio_jni_PFmodInterface
 * Method:    __set3dListenerTransform
 * Signature: (IFFFFFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_phonygames_pengine_audio_jni_PFmodInterface__1_1set3dListenerTransform
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_phonygames_pengine_audio_jni_PFmodInterface
 * Method:    __setEventInstance3dTransform
 * Signature: (JFFFFFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_phonygames_pengine_audio_jni_PFmodInterface__1_1setEventInstance3dTransform
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_phonygames_pengine_audio_jni_PFmodInterface
 * Method:    __setEventInstance3dPosition
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_com_phonygames_pengine_audio_jni_PFmodInterface__1_1setEventInstance3dPosition
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     com_phonygames_pengine_audio_jni_PFmodInterface
 * Method:    setEventInstanceParameterByName
 * Signature: (JLjava/lang/String;FZ)V
 */
JNIEXPORT void JNICALL Java_com_phonygames_pengine_audio_jni_PFmodInterface_setEventInstanceParameterByName
  (JNIEnv *, jclass, jlong, jstring, jfloat, jboolean);

#ifdef __cplusplus
}
#endif
#endif
